USE tutorialdb;

CREATE TABLE BST (
	N INT,
    P INT
    );
INSERT INTO BST (N, P)
VALUES ('1', '2');    
INSERT INTO BST (N, P)
VALUES ('3', '2');    
INSERT INTO BST (N, P)
VALUES ('5', '6');    
INSERT INTO BST (N, P)
VALUES ('7', '6');    
INSERT INTO BST (N, P)
VALUES ('2', '4');    
INSERT INTO BST (N, P)
VALUES ('6', '4');
INSERT INTO BST (N, P)
VALUES ('4', '15');
INSERT INTO BST (N, P)
VALUES ('8', '9');
INSERT INTO BST (N, P)
VALUES ('10', '9');
INSERT INTO BST (N, P)
VALUES ('12', '13');
INSERT INTO BST (N, P)
VALUES ('14', '13');
INSERT INTO BST (N, P)
VALUES ('9', '11');
INSERT INTO BST (N, P)
VALUES ('13', '11');
INSERT INTO BST (N, P)
VALUES ('11', '15');
INSERT INTO BST (N, P)
VALUES ('15', NULL);